services:
  mysagra-frontend:
    build:
      context: .
      dockerfile: ./docker/images/mysagra-frontend/Dockerfile
      args:
        - APP_NAME=MySagra
    depends_on:
      mysagra-backend:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://mysagra-backend:4300
      - ENABLE_TABLE_SERVICE=true
    restart: unless-stopped

  mysagra-backend:
    build:
      context: .
      dockerfile: ./docker/images/mysagra-backend/Dockerfile
    env_file: .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_URL=mysql://${DB_USER:-mysagra}:${DB_USER_PASSWORD:-mysagra}@db:3306/${MYSQL_DATABASE:-mysagra}
      - JWT_SECRET=${JWT_SECRET}
      - PEPPER=${PEPPER}
      - FRONTEND_URL=${FRONTEND_URL}
      - MIGRATE_ON_START=true
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4300/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    volumes:
      - api_logs:/app/logs
      - api_public:/app/public
    tmpfs:
      - /tmp
      - /run
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: mysql:latest
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: "${MYSQL_DATABASE:-mysagra}"
      MYSQL_USER: "${DB_USER:-mysagra}"
      MYSQL_PASSWORD: ${DB_USER_PASSWORD:-mysagra}
    volumes:
      - mysql_data:/var/lib/mysql:delegated
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
      - NET_BIND_SERVICE
    security_opt:
      - seccomp=unconfined
    user: mysql
volumes:
  api_logs:
    driver: local
  api_public:
    driver: local
  mysql_data:
    driver: local